from __future__ import annotations

from typing import Any

_PLAYBOOKS: dict[str, list[dict[str, Any]]] = {
    "identity.suspiciousSignIn": [
        {"step": 1, "title": "Review sign-in logs",
         "description": "Check recent authentication events across all identity providers for the user account",
         "priority": "high"},
        {"step": 2, "title": "Correlate IP geolocation",
         "description": "Map source IP addresses to known user locations and travel patterns",
         "priority": "high"},
        {"step": 3, "title": "Validate device compliance",
         "description": "Verify whether the sign-in device is registered, managed, and compliant",
         "priority": "medium"},
        {"step": 4, "title": "Contact user for verification",
         "description": "Reach out to the account owner to confirm or deny the sign-in activity",
         "priority": "high"},
        {"step": 5, "title": "Revoke sessions if malicious",
         "description": "Terminate all active sessions and force re-authentication if confirmed unauthorized",
         "priority": "critical"},
    ],
    "identity.passwordSpray": [
        {"step": 1, "title": "Identify targeted accounts",
         "description": "Enumerate all accounts included in the spray pattern",
         "priority": "high"},
        {"step": 2, "title": "Check successful authentications",
         "description": "Identify which accounts had successful logins during or after the spray",
         "priority": "critical"},
        {"step": 3, "title": "Reset compromised credentials",
         "description": "Force password reset for any accounts with successful attacker authentication",
         "priority": "critical"},
        {"step": 4, "title": "Block source IP addresses",
         "description": "Block the attacking IP addresses at the network perimeter and identity provider",
         "priority": "high"},
        {"step": 5, "title": "Review for lateral movement",
         "description": "Check for post-compromise activity from any successfully sprayed accounts",
         "priority": "high"},
    ],
    "identity.mfaFatigue": [
        {"step": 1, "title": "Contact user immediately",
         "description": "Verify with the account owner whether they initiated or approved any MFA prompts",
         "priority": "critical"},
        {"step": 2, "title": "Check approved prompts",
         "description": "Determine if any MFA challenge was accepted during the fatigue window",
         "priority": "critical"},
        {"step": 3, "title": "Reset MFA registration",
         "description": "Re-register MFA methods for the affected user account",
         "priority": "high"},
        {"step": 4, "title": "Investigate active sessions",
         "description": "Check for session theft or token replay resulting from any approved prompt",
         "priority": "high"},
        {"step": 5, "title": "Review device and location patterns",
         "description": "Validate device and IP patterns associated with the MFA prompts",
         "priority": "medium"},
    ],
    "identity.oauthConsentRisk": [
        {"step": 1, "title": "Review application permissions",
         "description": "Audit the scopes and permissions requested by the application",
         "priority": "high"},
        {"step": 2, "title": "Verify publisher legitimacy",
         "description": "Confirm the application publisher and its registration history",
         "priority": "high"},
        {"step": 3, "title": "Check consent history",
         "description": "Review tenant-wide consent patterns for the application",
         "priority": "medium"},
        {"step": 4, "title": "Revoke consent if unauthorized",
         "description": "Remove application consent and disable the enterprise application",
         "priority": "critical"},
        {"step": 5, "title": "Audit data access",
         "description": "Review what data was accessed by the application during the consent period",
         "priority": "high"},
    ],
    "identity.privilegeElevation": [
        {"step": 1, "title": "Validate change ticket",
         "description": "Confirm the role change against approved ITSM change requests",
         "priority": "high"},
        {"step": 2, "title": "Review actor authorization",
         "description": "Verify the actor has the authority to grant the assigned role",
         "priority": "high"},
        {"step": 3, "title": "Check for lateral movement",
         "description": "Look for follow-on suspicious activity using the elevated privileges",
         "priority": "high"},
        {"step": 4, "title": "Revert if unauthorized",
         "description": "Roll back the role assignment if no valid change ticket exists",
         "priority": "critical"},
        {"step": 5, "title": "Enable enhanced monitoring",
         "description": "Turn on heightened logging for the elevated account",
         "priority": "medium"},
    ],
    "endpoint.malwareDetection": [
        {"step": 1, "title": "Isolate affected endpoint",
         "description": "Network-isolate the host to prevent lateral spread of the malware",
         "priority": "critical"},
        {"step": 2, "title": "Quarantine detected file",
         "description": "Move the malware file to quarantine on the endpoint",
         "priority": "critical"},
        {"step": 3, "title": "Submit hash to threat intelligence",
         "description": "Upload the file hash for threat intelligence enrichment and community lookup",
         "priority": "high"},
        {"step": 4, "title": "Check for lateral spread",
         "description": "Scan other endpoints in the environment for the same indicators of compromise",
         "priority": "high"},
        {"step": 5, "title": "Review process execution chain",
         "description": "Analyze the process tree that led to the malware execution on the host",
         "priority": "medium"},
    ],
    "endpoint.suspiciousProcess": [
        {"step": 1, "title": "Isolate affected endpoint",
         "description": "Network-isolate the host to contain potential threat",
         "priority": "critical"},
        {"step": 2, "title": "Terminate suspicious process",
         "description": "Kill the suspicious process and any child processes",
         "priority": "critical"},
        {"step": 3, "title": "Collect process tree",
         "description": "Capture the full process ancestry and execution context",
         "priority": "high"},
        {"step": 4, "title": "Review command-line arguments",
         "description": "Analyze command-line flags, encoded content, and execution parameters",
         "priority": "high"},
        {"step": 5, "title": "Check for persistence mechanisms",
         "description": "Search for registry keys, scheduled tasks, or startup items set by the process",
         "priority": "medium"},
    ],
    "email.forwardingRule": [
        {"step": 1, "title": "Remove forwarding rule",
         "description": "Delete the suspicious mail forwarding rule immediately",
         "priority": "critical"},
        {"step": 2, "title": "Review mailbox access",
         "description": "Check login history and mailbox access patterns for the affected account",
         "priority": "high"},
        {"step": 3, "title": "Assess forwarded content",
         "description": "Determine what emails were forwarded and evaluate data exposure",
         "priority": "high"},
        {"step": 4, "title": "Reset credentials",
         "description": "Force password reset and revoke all active sessions for the mailbox owner",
         "priority": "critical"},
        {"step": 5, "title": "Enable audit logging",
         "description": "Turn on enhanced mailbox audit logging for ongoing monitoring",
         "priority": "medium"},
    ],
    "cloud.secretStoreAccessAnomaly": [
        {"step": 1, "title": "Review access logs",
         "description": "Audit the secret store access timeline and accessed resources",
         "priority": "high"},
        {"step": 2, "title": "Validate application identity",
         "description": "Confirm the application and its service principal are authorized for access",
         "priority": "high"},
        {"step": 3, "title": "Rotate exposed secrets",
         "description": "Rotate all secrets, keys, and certificates that may have been accessed",
         "priority": "critical"},
        {"step": 4, "title": "Check for data exfiltration",
         "description": "Look for evidence that accessed secrets were used externally",
         "priority": "high"},
        {"step": 5, "title": "Disable compromised tokens",
         "description": "Revoke tokens and disable the application if access was unauthorized",
         "priority": "critical"},
    ],
    "network.impossibleGeoAccess": [
        {"step": 1, "title": "Review authentication timeline",
         "description": "Map all authentication events by time and geographic location",
         "priority": "high"},
        {"step": 2, "title": "Correlate with travel records",
         "description": "Check against VPN usage, corporate travel, and known user locations",
         "priority": "high"},
        {"step": 3, "title": "Validate access locations",
         "description": "Confirm the legitimacy of each access point with the account owner",
         "priority": "high"},
        {"step": 4, "title": "Revoke suspicious sessions",
         "description": "Terminate sessions originating from the anomalous location",
         "priority": "critical"},
        {"step": 5, "title": "Apply conditional access",
         "description": "Implement location-based conditional access policies to prevent recurrence",
         "priority": "medium"},
    ],
    "cloud.iamPrivilegeEscalation": [
        {"step": 1, "title": "Validate change authorization",
         "description": "Check for an approved change ticket or CAB approval for the IAM role change",
         "priority": "critical"},
        {"step": 2, "title": "Audit escalated permissions",
         "description": "Review the granted role policies and determine the blast radius of the escalation",
         "priority": "high"},
        {"step": 3, "title": "Trace role assumption chain",
         "description": "Map the trust policy and identify the original principal that assumed the escalated role",
         "priority": "high"},
        {"step": 4, "title": "Revert unauthorized changes",
         "description": "Remove the escalated role assignment and restore the previous permission boundary",
         "priority": "critical"},
        {"step": 5, "title": "Review follow-on API activity",
         "description": "Audit all actions performed under the escalated role to assess impact",
         "priority": "high"},
    ],
    "cloud.suspiciousApiCall": [
        {"step": 1, "title": "Baseline API behavior",
         "description": "Compare the flagged API calls against the identity's 30-day historical baseline",
         "priority": "high"},
        {"step": 2, "title": "Analyze caller context",
         "description": "Review source IP, user agent, and session context for signs of attack tooling",
         "priority": "high"},
        {"step": 3, "title": "Assess data-plane impact",
         "description": "Determine if sensitive data was accessed or modified by the suspicious calls",
         "priority": "critical"},
        {"step": 4, "title": "Restrict API access",
         "description": "Apply temporary deny policies to block further suspicious API activity",
         "priority": "critical"},
        {"step": 5, "title": "Trace identity origin",
         "description": "If from an assumed role, trace the trust chain back to the originating identity",
         "priority": "medium"},
    ],
    "email.phishingDetected": [
        {"step": 1, "title": "Quarantine phishing emails",
         "description": "Remove the phishing email from all recipient inboxes across the tenant",
         "priority": "critical"},
        {"step": 2, "title": "Block sender and URLs",
         "description": "Add the sender domain and embedded URLs to the email gateway and proxy block lists",
         "priority": "critical"},
        {"step": 3, "title": "Identify impacted users",
         "description": "Determine which recipients opened or interacted with the phishing email",
         "priority": "high"},
        {"step": 4, "title": "Reset compromised credentials",
         "description": "Force password reset and revoke tokens for users who submitted credentials",
         "priority": "critical"},
        {"step": 5, "title": "Notify and educate recipients",
         "description": "Send a security advisory to all recipients with phishing indicators and guidance",
         "priority": "medium"},
    ],
    "network.dataExfiltration": [
        {"step": 1, "title": "Block exfiltration channel",
         "description": "Block the external destination IP or domain at the network perimeter immediately",
         "priority": "critical"},
        {"step": 2, "title": "Quantify data exposure",
         "description": "Determine the volume, type, and classification of data transferred externally",
         "priority": "critical"},
        {"step": 3, "title": "Identify data sources",
         "description": "Trace the accessed files and repositories to determine the scope of the breach",
         "priority": "high"},
        {"step": 4, "title": "Assess insider threat indicators",
         "description": "Check for HR flags such as resignation, performance issues, or access anomalies",
         "priority": "high"},
        {"step": 5, "title": "Engage legal and compliance",
         "description": "Coordinate with legal and compliance teams for breach notification assessment",
         "priority": "medium"},
    ],
    "identity.impossibleTravel": [
        {"step": 1, "title": "Map geographic timeline",
         "description": "Plot all authentication events by time and location to confirm impossible travel distance",
         "priority": "critical"},
        {"step": 2, "title": "Check VPN and proxy usage",
         "description": "Determine if either IP belongs to a known VPN or proxy service that explains the anomaly",
         "priority": "high"},
        {"step": 3, "title": "Compare device fingerprints",
         "description": "Check if the same device ID appears from both locations indicating token theft",
         "priority": "high"},
        {"step": 4, "title": "Kill suspicious session",
         "description": "Terminate the newer session and force re-authentication with MFA from the verified location",
         "priority": "critical"},
        {"step": 5, "title": "Contact user out-of-band",
         "description": "Verify the user's actual location and travel schedule via phone call, not email",
         "priority": "medium"},
    ],
    "identity.dormantAccountLogin": [
        {"step": 1, "title": "Verify account status",
         "description": "Confirm the account's dormancy period and check if reactivation was authorized",
         "priority": "critical"},
        {"step": 2, "title": "Review authentication details",
         "description": "Check source IP, device, and location for the dormant account login",
         "priority": "high"},
        {"step": 3, "title": "Check credential exposure",
         "description": "Search for the account's credentials in known breach databases and dark web feeds",
         "priority": "high"},
        {"step": 4, "title": "Disable if unauthorized",
         "description": "Disable the account and reset credentials if reactivation was not approved",
         "priority": "critical"},
        {"step": 5, "title": "Audit recent activity",
         "description": "Review all activity from this account in the last 24 hours for signs of compromise",
         "priority": "high"},
    ],
    "identity.serviceAccountAbuse": [
        {"step": 1, "title": "Identify logon type",
         "description": "Determine if the service account was used for interactive logon or remote desktop",
         "priority": "critical"},
        {"step": 2, "title": "Validate source host",
         "description": "Compare the source host against the known baseline of authorized service hosts",
         "priority": "high"},
        {"step": 3, "title": "Check credential harvesting",
         "description": "Look for evidence of credential theft (T1003) on endpoints that use this service account",
         "priority": "high"},
        {"step": 4, "title": "Disable if compromised",
         "description": "Disable the service account and rotate credentials if abuse is confirmed",
         "priority": "critical"},
        {"step": 5, "title": "Audit permissions and access",
         "description": "Review all service account permissions and enforce principle of least privilege",
         "priority": "medium"},
    ],
    "email.businessEmailCompromise": [
        {"step": 1, "title": "Alert finance team",
         "description": "Immediately notify finance to hold all pending wire transfers and payment requests",
         "priority": "critical"},
        {"step": 2, "title": "Verify sender domain",
         "description": "Check domain registration date, WHOIS data, and compare against legitimate sender domain",
         "priority": "high"},
        {"step": 3, "title": "Analyze email headers",
         "description": "Compare sender email headers, reply-to addresses, and routing against known correspondence",
         "priority": "high"},
        {"step": 4, "title": "Search for campaign scope",
         "description": "Find all emails from the same sender domain to determine how many employees were targeted",
         "priority": "high"},
        {"step": 5, "title": "Initiate wire recall if needed",
         "description": "If funds were transferred, initiate wire recall immediately within the 24-72 hour banking window",
         "priority": "critical"},
    ],
    "email.maliciousAttachment": [
        {"step": 1, "title": "Quarantine attachment",
         "description": "Remove all emails containing the malicious attachment hash from recipient inboxes",
         "priority": "critical"},
        {"step": 2, "title": "Check endpoint execution",
         "description": "Determine if any recipient opened the attachment and check for execution artifacts",
         "priority": "critical"},
        {"step": 3, "title": "Sandbox analysis",
         "description": "Submit the attachment to VirusTotal and sandbox for malware family identification",
         "priority": "high"},
        {"step": 4, "title": "Isolate compromised endpoints",
         "description": "Network-isolate any endpoint where the attachment was opened and executed",
         "priority": "critical"},
        {"step": 5, "title": "Block sender and indicators",
         "description": "Add sender domain, file hash, and any C2 indicators to block lists",
         "priority": "high"},
    ],
    "cloud.resourceHijacking": [
        {"step": 1, "title": "Terminate unauthorized workloads",
         "description": "Kill crypto mining processes and terminate unauthorized containers or instances",
         "priority": "critical"},
        {"step": 2, "title": "Isolate compromised resources",
         "description": "Network-isolate the hijacked instance and revoke associated IAM credentials",
         "priority": "critical"},
        {"step": 3, "title": "Audit entry vector",
         "description": "Determine how the attacker gained access -- exposed credentials, misconfigured service, or container escape",
         "priority": "high"},
        {"step": 4, "title": "Scan for lateral spread",
         "description": "Check other instances in the VPC for similar mining processes or backdoors",
         "priority": "high"},
        {"step": 5, "title": "Review billing and harden",
         "description": "Assess financial impact from compute abuse and deploy preventive controls",
         "priority": "medium"},
    ],
    "cloud.dataExposure": [
        {"step": 1, "title": "Remediate public access",
         "description": "Remove public access from the exposed storage bucket or container immediately",
         "priority": "critical"},
        {"step": 2, "title": "Inventory exposed data",
         "description": "Catalog all objects in the exposed storage and determine data classification levels",
         "priority": "critical"},
        {"step": 3, "title": "Review access logs",
         "description": "Analyze storage access logs for unauthorized external downloads during the exposure window",
         "priority": "high"},
        {"step": 4, "title": "Assess regulatory impact",
         "description": "Determine if PII, PHI, or PCI data was exposed and evaluate notification requirements",
         "priority": "high"},
        {"step": 5, "title": "Deploy preventive controls",
         "description": "Implement SCPs, organization policies, or guardrails to prevent future public storage",
         "priority": "medium"},
    ],
    "network.commandAndControl": [
        {"step": 1, "title": "Isolate affected host",
         "description": "Network-isolate the host communicating with C2 infrastructure to stop attacker access",
         "priority": "critical"},
        {"step": 2, "title": "Block C2 destination",
         "description": "Block the C2 IP address and domain at firewall, proxy, and DNS resolver",
         "priority": "critical"},
        {"step": 3, "title": "Analyze beaconing pattern",
         "description": "Examine connection intervals, payload sizes, and TLS certificates to identify the C2 framework",
         "priority": "high"},
        {"step": 4, "title": "Sweep for additional victims",
         "description": "Search proxy and firewall logs for other hosts communicating with the same C2 infrastructure",
         "priority": "high"},
        {"step": 5, "title": "Collect forensic artifacts",
         "description": "Capture memory dump, process tree, and persistence mechanisms from the compromised host",
         "priority": "medium"},
    ],
    "network.portScan": [
        {"step": 1, "title": "Identify scanner and authorization",
         "description": "Determine if the scan source is internal or external and verify against authorized scan schedules",
         "priority": "high"},
        {"step": 2, "title": "Block unauthorized scanner",
         "description": "Block the scanning IP at the network perimeter if no authorization exists",
         "priority": "critical"},
        {"step": 3, "title": "Assess scan scope",
         "description": "Determine which hosts and ports were scanned and identify any services that responded",
         "priority": "high"},
        {"step": 4, "title": "Investigate internal scanner",
         "description": "If internal host is scanning, check for compromise indicators -- malware, C2, or lateral movement",
         "priority": "high"},
        {"step": 5, "title": "Harden exposed services",
         "description": "Review services that responded to the scan for vulnerabilities and apply patches or firewall rules",
         "priority": "medium"},
    ],
    "network.dnsAnomaly": [
        {"step": 1, "title": "Block suspicious domain",
         "description": "Sinkhole the anomalous domain at the DNS resolver to stop data exfiltration",
         "priority": "critical"},
        {"step": 2, "title": "Isolate source host",
         "description": "Network-isolate the host generating anomalous DNS queries",
         "priority": "critical"},
        {"step": 3, "title": "Analyze DNS query content",
         "description": "Decode high-entropy subdomains and TXT record payloads to determine exfiltrated data",
         "priority": "high"},
        {"step": 4, "title": "Identify affected clients",
         "description": "Search DNS resolver logs for all clients that queried the suspicious domain",
         "priority": "high"},
        {"step": 5, "title": "Assess data loss",
         "description": "Estimate the volume and sensitivity of data exfiltrated via the DNS channel",
         "priority": "medium"},
    ],
    "dlp.sensitiveDataExposure": [
        {"step": 1, "title": "Contain data exposure",
         "description": "Remove or restrict access to the sensitive data in the unauthorized location immediately",
         "priority": "critical"},
        {"step": 2, "title": "Classify exposed data",
         "description": "Determine the classification level (PII, PHI, PCI) and volume of exposed data",
         "priority": "critical"},
        {"step": 3, "title": "Investigate user activity",
         "description": "Review the user's recent file access, transfers, and DLP policy violations",
         "priority": "high"},
        {"step": 4, "title": "Assess insider threat indicators",
         "description": "Check for resignation on file, performance issues, or anomalous access patterns",
         "priority": "high"},
        {"step": 5, "title": "Engage compliance and legal",
         "description": "Coordinate with compliance and legal teams for regulatory breach notification assessment",
         "priority": "medium"},
    ],
    "endpoint.ransomwareDetection": [
        {"step": 1, "title": "Isolate affected endpoint",
         "description": "Immediately network-isolate the host to stop ransomware from spreading to other systems",
         "priority": "critical"},
        {"step": 2, "title": "Check for shadow copy deletion",
         "description": "Query for vssadmin or bcdedit commands indicating active ransomware destroying backups",
         "priority": "critical"},
        {"step": 3, "title": "Identify ransomware family",
         "description": "Determine the variant from ransom note, encrypted file extensions, or IOC matching",
         "priority": "high"},
        {"step": 4, "title": "Assess lateral spread",
         "description": "Scan all endpoints in the same subnet for matching IOCs and encryption activity",
         "priority": "high"},
        {"step": 5, "title": "Verify backup integrity",
         "description": "Confirm offline backups are intact and uncompromised before beginning recovery",
         "priority": "critical"},
    ],
    "endpoint.lateralMovement": [
        {"step": 1, "title": "Block source host",
         "description": "Block the source host from making further remote connections to other endpoints",
         "priority": "critical"},
        {"step": 2, "title": "Map movement path",
         "description": "Document the full lateral movement chain from source through pivots to destination hosts",
         "priority": "high"},
        {"step": 3, "title": "Investigate credential source",
         "description": "Determine how the attacker obtained credentials used for lateral movement",
         "priority": "high"},
        {"step": 4, "title": "Isolate compromised hosts",
         "description": "Network-isolate all hosts that were accessed during the lateral movement campaign",
         "priority": "critical"},
        {"step": 5, "title": "Check for data staging",
         "description": "Review all accessed systems for evidence of data staging or exfiltration preparation",
         "priority": "high"},
    ],
    "endpoint.credentialDumping": [
        {"step": 1, "title": "Isolate compromised host",
         "description": "Network-isolate the host where credential dumping was detected",
         "priority": "critical"},
        {"step": 2, "title": "Identify dumped credentials",
         "description": "Determine which accounts were cached on the host and assume all are compromised",
         "priority": "critical"},
        {"step": 3, "title": "Force password resets",
         "description": "Reset passwords for all accounts that were logged into the compromised host",
         "priority": "critical"},
        {"step": 4, "title": "Check for DCSync",
         "description": "If domain controller was targeted, verify whether all domain hashes were extracted",
         "priority": "high"},
        {"step": 5, "title": "Deploy credential protections",
         "description": "Enable Credential Guard and LSASS protection across affected endpoints",
         "priority": "high"},
    ],
    "endpoint.persistenceMechanism": [
        {"step": 1, "title": "Disable persistence mechanism",
         "description": "Remove or disable the suspicious scheduled task, service, or registry modification",
         "priority": "critical"},
        {"step": 2, "title": "Preserve artifact for analysis",
         "description": "Collect the persistence payload, command line, and creation metadata for forensic review",
         "priority": "high"},
        {"step": 3, "title": "Analyze payload",
         "description": "Check the task or service command line for encoded payloads, download cradles, or C2 URLs",
         "priority": "high"},
        {"step": 4, "title": "Compare against baseline",
         "description": "Verify whether the persistence mechanism matches known administrative tools or is attacker-created",
         "priority": "medium"},
        {"step": 5, "title": "Scan for additional persistence",
         "description": "Search for registry run keys, startup folder entries, and WMI subscriptions on the host",
         "priority": "high"},
    ],
    "endpoint.defenseEvasion": [
        {"step": 1, "title": "Restore security controls",
         "description": "Re-enable any disabled AV, EDR, or logging mechanisms on the affected endpoint",
         "priority": "critical"},
        {"step": 2, "title": "Identify disabling actor",
         "description": "Determine which user or process disabled the security controls and when",
         "priority": "critical"},
        {"step": 3, "title": "Check for cleared logs",
         "description": "Verify whether event logs were cleared and recover copies from centralized SIEM",
         "priority": "high"},
        {"step": 4, "title": "Hunt for evasion artifacts",
         "description": "Search for AMSI bypass, ETW patching, process injection, or DLL hollowing indicators",
         "priority": "high"},
        {"step": 5, "title": "Validate environment controls",
         "description": "Verify all security controls are operational across the entire environment",
         "priority": "medium"},
    ],
}


def get_playbook(alert_type: str) -> list[dict[str, Any]]:
    return list(_PLAYBOOKS.get(alert_type, []))
