"""initial schema

Revision ID: cb053e5f88d7
Revises: 
Create Date: 2026-04-05 08:05:39.474501+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb053e5f88d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('calibration_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analyst_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analyst', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('signals_fired', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_feedback_alert_type'), 'calibration_feedback', ['alert_type'], unique=False)
    op.create_index(op.f('ix_calibration_feedback_case_id'), 'calibration_feedback', ['case_id'], unique=False)
    op.create_table('signal_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signals_fired', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('source_tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_risk_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cross_alert_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_telemetry_alert_type'), 'signal_telemetry', ['alert_type'], unique=False)
    op.create_table('suppression_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('hits_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_rules_tenant_id'), 'suppression_rules', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('ingested_time', sa.DateTime(), nullable=False),
    sa.Column('enriched_time', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('confidence_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('enrichment', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommended_playbook', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommended_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('outputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('audit', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('bulk_target', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('disposition_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disposition_set_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disposition_set_at', sa.DateTime(), nullable=True),
    sa.Column('disposition_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retention_store_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retention_ttl_days', sa.Integer(), nullable=False),
    sa.Column('retention_redacted', sa.Boolean(), nullable=False),
    sa.Column('time_to_first_decision_ms', sa.Integer(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('grouping_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('member_alert_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_alert_type'), 'cases', ['alert_type'], unique=False)
    op.create_index(op.f('ix_cases_grouping_key'), 'cases', ['grouping_key'], unique=False)
    op.create_index(op.f('ix_cases_schema_version'), 'cases', ['schema_version'], unique=False)
    op.create_index(op.f('ix_cases_tenant_id'), 'cases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cases_time_to_first_decision_ms'), 'cases', ['time_to_first_decision_ms'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('confidence_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('kill_chain_stages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('kill_chain_gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('linkage_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('link_strength', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommended_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('workflow', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('alert_type_count', sa.Integer(), nullable=False),
    sa.Column('time_span_seconds', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('case_confidence_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('signal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_confidence_signals_case_id'), 'case_confidence_signals', ['case_id'], unique=False)
    op.create_table('case_disposition_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ttfd_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_disposition_events_case_id'), 'case_disposition_events', ['case_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('case_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_alert_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_sources_case_id'), 'case_sources', ['case_id'], unique=False)
    op.create_table('incident_case_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('kill_chain_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_case_links_case_id'), 'incident_case_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_incident_case_links_incident_id'), 'incident_case_links', ['incident_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_case_id'), 'webhook_deliveries', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_case_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_incident_case_links_incident_id'), table_name='incident_case_links')
    op.drop_index(op.f('ix_incident_case_links_case_id'), table_name='incident_case_links')
    op.drop_table('incident_case_links')
    op.drop_index(op.f('ix_case_sources_case_id'), table_name='case_sources')
    op.drop_table('case_sources')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_case_disposition_events_case_id'), table_name='case_disposition_events')
    op.drop_table('case_disposition_events')
    op.drop_index(op.f('ix_case_confidence_signals_case_id'), table_name='case_confidence_signals')
    op.drop_table('case_confidence_signals')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_cases_time_to_first_decision_ms'), table_name='cases')
    op.drop_index(op.f('ix_cases_tenant_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_schema_version'), table_name='cases')
    op.drop_index(op.f('ix_cases_grouping_key'), table_name='cases')
    op.drop_index(op.f('ix_cases_alert_type'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_suppression_rules_tenant_id'), table_name='suppression_rules')
    op.drop_table('suppression_rules')
    op.drop_index(op.f('ix_signal_telemetry_alert_type'), table_name='signal_telemetry')
    op.drop_table('signal_telemetry')
    op.drop_index(op.f('ix_calibration_feedback_case_id'), table_name='calibration_feedback')
    op.drop_index(op.f('ix_calibration_feedback_alert_type'), table_name='calibration_feedback')
    op.drop_table('calibration_feedback')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
